<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Gst.Video</RootNamespace>
    <Description>GstVideo for GstSharp.Net: video formats, video info and the video metas.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GstSharp.Net/GstSharp.Net.csproj" />
    <ProjectReference Include="../GstSharp.Net.Base/GstSharp.Net.Base.csproj" />
  </ItemGroup>

</Project>
