using GstSharp.Generator.Emit;
using GstSharp.Generator.GirParsing;
using GstSharp.Generator.GirParsing.Model;
using GstSharp.Generator.Semantic;
using Xunit;

namespace GstSharp.Generator.Tests;

/// <summary>
/// Output shape and determinism of the enumeration emitter.
/// </summary>
public sealed class EnumEmitterTests
{
    private static readonly ModuleInfo GstModule = ModuleMap.Find("Gst")!;

    [Fact]
    public void EmittingTwiceProducesIdenticalOutput()
    {
        GirNamespace gst = GirFixture.Namespace("Gst");

        string first = Emit(gst);
        string second = Emit(gst);

        Assert.Equal(first, second, StringComparer.Ordinal);
    }

    [Fact]
    public void FileHeaderNamesTheSourceGirWithoutATimestamp()
    {
        string source = Emit(GirFixture.Namespace("Gst"));

        Assert.StartsWith(
            "// <auto-generated/>\n// Generated by GstSharp.Generator from Gst-1.0.gir. Do not edit.\n",
            source,
            StringComparison.Ordinal);
        Assert.Contains("\nnamespace Gst;\n", source, StringComparison.Ordinal);
        Assert.DoesNotContain("\r", source, StringComparison.Ordinal);
        Assert.EndsWith("}\n", source, StringComparison.Ordinal);
    }

    [Fact]
    public void EveryEnumerationOfTheNamespaceIsEmitted()
    {
        GirNamespace gst = GirFixture.Namespace("Gst");
        string source = Emit(gst);

        int declarations = source.Split("\npublic enum ", StringSplitOptions.None).Length - 1;
        Assert.Equal(gst.Enumerations.Count + gst.Bitfields.Count, declarations);
    }

    [Fact]
    public void BitfieldsGetFlagsAndHexadecimalValues()
    {
        string source = Emit(GirFixture.Namespace("Gst"));

        Assert.Contains("[Flags]\npublic enum SeekFlags\n", source, StringComparison.Ordinal);
        Assert.Contains("    Flush = 0x00000001,\n", source, StringComparison.Ordinal);
    }

    [Fact]
    public void BitfieldsThatUseBitThirtyOneBecomeUInt32()
    {
        string source = Emit(GirFixture.Namespace("Gst"));

        Assert.Contains("public enum MessageType : uint\n", source, StringComparison.Ordinal);
        Assert.Contains("    Any = 0xFFFFFFFF,\n", source, StringComparison.Ordinal);
    }

    [Fact]
    public void PlainEnumerationsKeepDecimalAndSignedValues()
    {
        string source = Emit(GirFixture.Namespace("Gst"));

        Assert.Contains("public enum FlowReturn\n", source, StringComparison.Ordinal);
        Assert.Contains("    Eos = -3,\n", source, StringComparison.Ordinal);
        Assert.Contains("    Ok = 0,\n", source, StringComparison.Ordinal);
    }

    [Fact]
    public void TypesAreOrderedByTheirCSharpName()
    {
        string source = Emit(GirFixture.Namespace("Gst"));

        List<string> names = [];
        foreach (string line in source.Split('\n'))
        {
            if (line.StartsWith("public enum ", StringComparison.Ordinal))
            {
                string rest = line["public enum ".Length..];
                int colon = rest.IndexOf(' ', StringComparison.Ordinal);
                names.Add(colon < 0 ? rest : rest[..colon]);
            }
        }

        Assert.NotEmpty(names);
        Assert.Equal(names.Order(StringComparer.Ordinal).ToList(), names);
    }

    [Fact]
    public void MembersWithoutDocumentationGetAFallbackSummary()
    {
        string source = EmitFixture(
            """
            <enumeration name="Kind" c:type="TestKind">
              <member name="first" value="0" c:identifier="TEST_KIND_FIRST"/>
            </enumeration>
            """);

        Assert.Contains("/// <summary>The <c>TestKind</c> enumeration.</summary>", source, StringComparison.Ordinal);
        Assert.Contains("/// <summary>The <c>TEST_KIND_FIRST</c> value.</summary>", source, StringComparison.Ordinal);
    }

    [Fact]
    public void DocumentationIsEscapedAndSplitIntoSummaryAndRemarks()
    {
        string source = EmitFixture(
            """
            <enumeration name="Kind" c:type="TestKind">
              <doc xml:space="preserve">Compares a &lt;value&gt; with &amp; inside.

            More detail.</doc>
              <member name="first" value="0" c:identifier="TEST_KIND_FIRST"/>
            </enumeration>
            """);

        Assert.Contains(
            "/// <summary>Compares a &lt;value&gt; with &amp; inside.</summary>",
            source,
            StringComparison.Ordinal);
        Assert.Contains("/// <remarks>\n/// <para>More detail.</para>\n/// </remarks>", source, StringComparison.Ordinal);
    }

    [Fact]
    public void RepeatedMembersAreEmittedOnce()
    {
        // GstVideo repeats members verbatim, for example onefield in
        // GstVideoFrameFlags.
        string source = EmitFixture(
            """
            <bitfield name="Mask" c:type="TestMask">
              <member name="onefield" value="8" c:identifier="TEST_MASK_ONEFIELD"/>
              <member name="top_field" value="10" c:identifier="TEST_MASK_TOP_FIELD"/>
              <member name="onefield" value="8" c:identifier="TEST_MASK_ONEFIELD"/>
            </bitfield>
            """);

        int occurrences = source.Split("    Onefield = ", StringSplitOptions.None).Length - 1;
        Assert.Equal(1, occurrences);
        Assert.Contains("    TopField = 0x0000000A,", source, StringComparison.Ordinal);
    }

    [Fact]
    public void LeadingDigitMembersGetAnUnderscore()
    {
        string source = EmitFixture(
            """
            <enumeration name="Range" c:type="TestRange">
              <member name="16_235" value="1" c:identifier="TEST_RANGE_16_235"/>
            </enumeration>
            """);

        Assert.Contains("    _16235 = 1,", source, StringComparison.Ordinal);
    }

    [Fact]
    public void DeprecatedEnumerationsGetAnObsoleteAttribute()
    {
        string source = EmitFixture(
            """
            <enumeration name="Old" c:type="TestOld" deprecated="1" deprecated-version="1.28">
              <doc-deprecated xml:space="preserve">Use TestNew
            instead.</doc-deprecated>
              <member name="first" value="0" c:identifier="TEST_OLD_FIRST"/>
            </enumeration>
            """);

        Assert.Contains(
            "[Obsolete(\"Use TestNew instead. (deprecated since 1.28)\")]",
            source,
            StringComparison.Ordinal);
    }

    [Fact]
    public void NamespacesWithoutEnumerationsEmitNothing()
    {
        GirNamespace ns = GirReader.ReadXml(
            """
            <repository xmlns="http://www.gtk.org/introspection/core/1.0" xmlns:c="http://www.gtk.org/introspection/c/1.0" xmlns:glib="http://www.gtk.org/introspection/glib/1.0" version="1.2">
              <namespace name="Test" version="1.0" c:identifier-prefixes="Test" c:symbol-prefixes="test"/>
            </repository>
            """,
            "fixture.gir").Namespaces[0];

        EnumEmitter emitter = new(new NameMapper(Overlays.Empty), Overlays.Empty, new DiagnosticBag());
        Assert.Null(emitter.Emit(GstModule, ns));
    }

    // The diff gate of the committed sources. It is off until the tree below
    // src/ is refreshed with
    //   dotnet run --project generator/GstSharp.Generator -- generate --gir-dir girs --out-dir src
    // which is the step that integrates the rejections of this milestone: the
    // members that corrupted memory disappear, forty nine private state shells
    // stop being emitted, the global holder of an extension module is renamed
    // and every instance member gains its GC.KeepAlive. Remove the Skip
    // together with that regeneration.
    [Fact]
    public void TheCommittedFilesMatchTheEmitter()
    {
        IReadOnlyList<GeneratedFile> files = GenerationPipeline.Run(GirFixture.GirDirectory).Files;

        Assert.NotEmpty(files);
        foreach (GeneratedFile file in files)
        {
            string committed = File.ReadAllText(
                Path.Combine(GirFixture.RepositoryRoot, "src", file.RelativePath.Replace('/', Path.DirectorySeparatorChar)));

            Assert.Equal(file.Content, committed.Replace("\r\n", "\n", StringComparison.Ordinal), StringComparer.Ordinal);
        }
    }

    private static string Emit(GirNamespace ns)
    {
        EnumEmitter emitter = new(new NameMapper(Overlays.Empty), Overlays.Empty, new DiagnosticBag());
        GeneratedFile file = emitter.Emit(GstModule, ns)
            ?? throw new InvalidOperationException("The namespace produced no output.");
        return file.Content;
    }

    private static string EmitFixture(string body)
    {
        GirNamespace ns = GirReader.ReadXml(
            $"""
            <repository xmlns="http://www.gtk.org/introspection/core/1.0" xmlns:c="http://www.gtk.org/introspection/c/1.0" xmlns:glib="http://www.gtk.org/introspection/glib/1.0" version="1.2">
              <namespace name="Test" version="1.0" c:identifier-prefixes="Test" c:symbol-prefixes="test">
            {body}
              </namespace>
            </repository>
            """,
            "fixture.gir").Namespaces[0];

        return Emit(ns);
    }
}
