namespace GstSharp.Generator.Tests;

/// <summary>
/// A gir directory and an output directory of their own, and the verbs run
/// over them through the console entry point.
/// </summary>
/// <remarks>
/// The gir it plants holds one bindable class, small enough that a run over it
/// costs a few milliseconds. The modules it does not declare are reported as
/// GEN0005 warnings and emit nothing, which is exactly the shape the command
/// line tests need: one generated directory with a handful of files in it.
/// </remarks>
internal sealed class GeneratorWorkspace : IDisposable
{
    private const string Gir =
        $"""
        <repository xmlns="http://www.gtk.org/introspection/core/1.0" xmlns:c="http://www.gtk.org/introspection/c/1.0" xmlns:glib="http://www.gtk.org/introspection/glib/1.0" version="1.2">
          <namespace name="Gst" version="1.0" c:identifier-prefixes="Gst" c:symbol-prefixes="gst">
            <class name="Widget" c:type="GstWidget" parent="GObject.InitiallyUnowned" glib:type-name="GstWidget" glib:get-type="gst_widget_get_type">
              <method name="pack" c:identifier="gst_widget_pack">
                <return-value transfer-ownership="none">
                  <type name="gboolean" c:type="gboolean"/>
                </return-value>
                <parameters>
                  <instance-parameter name="widget" transfer-ownership="none">
                    <type name="Widget" c:type="GstWidget*"/>
                  </instance-parameter>
                </parameters>
              </method>
            </class>
          </namespace>
        {Fixture.GObjectNamespace}
        </repository>
        """;

    private readonly string _root =
        Path.Combine(Path.GetTempPath(), "GstSharp.Generator.Tests", Path.GetRandomFileName());

    internal GeneratorWorkspace()
    {
        Directory.CreateDirectory(Path.Combine(_root, "girs", "reference"));
        Directory.CreateDirectory(OutputDirectory);
        File.WriteAllText(Path.Combine(_root, "girs", "reference", "Gst-1.0.gir"), Gir);
    }

    /// <summary>Gets the directory the verbs write the sources into.</summary>
    internal string OutputDirectory => Path.Combine(_root, "src");

    /// <summary>Gets the directory the verbs read the gir files from.</summary>
    internal string GirDirectory => Path.Combine(_root, "girs");

    /// <summary>Writes a source into the generated directory of the module.</summary>
    /// <param name="name">The file name.</param>
    /// <returns>The path it was written to.</returns>
    internal string Plant(string name)
    {
        string directory = Path.Combine(OutputDirectory, "GstSharp.Net", "Generated");
        Directory.CreateDirectory(directory);
        string path = Path.Combine(directory, name);
        File.WriteAllText(path, "// Generated by a run that no longer exists.\n");
        return path;
    }

    /// <summary>Runs one verb over the workspace.</summary>
    /// <param name="verb">The verb to run.</param>
    /// <param name="exitCode">Receives the exit code.</param>
    /// <param name="reportDirectory">
    /// The directory the skip report belongs in, or <see langword="null"/> to
    /// leave it where the gir files are.
    /// </param>
    /// <returns>Everything the run wrote to the console.</returns>
    internal string Run(string verb, out int exitCode, string? reportDirectory = null)
    {
        List<string> args = [verb, "--gir-dir", GirDirectory, "--out-dir", OutputDirectory];
        if (reportDirectory is not null)
        {
            args.Add("--report-dir");
            args.Add(reportDirectory);
        }

        TextWriter previousOut = Console.Out;
        TextWriter previousError = Console.Error;
        StringWriter captured = new();
        try
        {
            Console.SetOut(captured);
            Console.SetError(captured);
            exitCode = Program.Main([.. args]);
        }
        finally
        {
            Console.SetOut(previousOut);
            Console.SetError(previousError);
        }

        return captured.ToString();
    }

    public void Dispose()
    {
        if (Directory.Exists(_root))
        {
            Directory.Delete(_root, recursive: true);
        }
    }
}
