<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Gst.Audio</RootNamespace>
    <Description>GstAudio for GstSharp.Net: audio formats, audio info, the audio metas and the ring buffer.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GstSharp.Net/GstSharp.Net.csproj" />
    <ProjectReference Include="../GstSharp.Net.Base/GstSharp.Net.Base.csproj" />
  </ItemGroup>

</Project>
