<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Gst.Base</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GstSharp.Net.Core/GstSharp.Net.Core.csproj" />
    <ProjectReference Include="../GstSharp.Net/GstSharp.Net.csproj" />
  </ItemGroup>

</Project>
