<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>GstSharp.Samples.RtpPacketDump</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/GstSharp.Net/GstSharp.Net.csproj" />
    <ProjectReference Include="../../src/GstSharp.Net.App/GstSharp.Net.App.csproj" />
    <ProjectReference Include="../../src/GstSharp.Net.Rtp/GstSharp.Net.Rtp.csproj" />
  </ItemGroup>

</Project>
