<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Gst.Sdp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GstSharp.Net/GstSharp.Net.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GstSharp.Net.WebRTC" />
  </ItemGroup>

</Project>
