using GstSharp.Generator.GirParsing.Model;
using GstSharp.Generator.Planning;
using GstSharp.Generator.Semantic;

namespace GstSharp.Generator.Emit;

/// <summary>
/// Emits the delegate types and the trampolines of the callbacks that the
/// generated members take.
/// </summary>
/// <remarks>
/// Only the callbacks that a planned callable actually uses are emitted: a
/// delegate that nothing can be handed to is dead surface, and several of the
/// callbacks of a gir namespace are vtable slots that this milestone cannot
/// bind anyway.
/// </remarks>
internal sealed class CallbackEmitter
{
    private readonly MarshalPlanner _planner;
    private readonly EmissionCensus _census;

    /// <summary>Initializes a new instance of the <see cref="CallbackEmitter"/> class.</summary>
    /// <param name="planner">The planner that collected the used callbacks.</param>
    /// <param name="census">The census of the run.</param>
    internal CallbackEmitter(MarshalPlanner planner, EmissionCensus census)
    {
        _planner = planner;
        _census = census;
    }

    /// <summary>Emits the callbacks of one module.</summary>
    /// <param name="module">The module to emit.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <returns>The generated file, or <see langword="null"/> when no callback is used.</returns>
    internal GeneratedFile? Emit(ModuleInfo module, GirNamespace ns)
    {
        if (_planner.UsedCallbacks.Count == 0)
        {
            return null;
        }

        CodeWriter writer = new();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("// Generated by GstSharp.Generator from " + ns.Name + "-" + ns.Version + ".gir. Do not edit.");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Runtime.CompilerServices;");
        writer.WriteLine("using System.Runtime.InteropServices;");
        writer.WriteLine();
        writer.WriteLine("namespace " + module.ClrNamespace + ";");

        foreach (KeyValuePair<string, CallbackPlan> entry in _planner.UsedCallbacks)
        {
            writer.WriteLine();
            CallableRenderer.WriteCallback(writer, entry.Value);
            _census.Emitted(module.GirNamespace, "callback");
        }

        return new GeneratedFile(module.ProjectDirectory + "/Generated/Callbacks.cs", writer.ToSource());
    }
}
