using GstSharp.Generator.GirParsing.Model;
using GstSharp.Generator.Semantic;

namespace GstSharp.Generator.Emit;

/// <summary>
/// Emits the managed mirror of a class struct, one file per class.
/// </summary>
/// <remarks>
/// <para>
/// The runtime does exactly one thing with a class struct: it writes a function
/// pointer at a computed offset. Everything else the mirror carries is there so
/// that the offset comes out right, which is why the mirror lays out every
/// field the gir declares — the data fields a <c>class_init</c> writes, the
/// slots nothing overrides, and the reserved tail — and why no field of it is
/// ever a typed <c>delegate*</c>: a slot is read as an <see langword="nint"/>
/// and cast at the point of use.
/// </para>
/// <para>
/// The offsets are measured from the mirror at run time rather than written out
/// as literals, so a declaration cannot drift from the layout; the layout
/// itself is what the ABI probes pin to the running library.
/// </para>
/// </remarks>
internal sealed class ClassStructEmitter
{
    /// <summary>The directory the mirrors are written to, below <c>Generated</c>.</summary>
    internal const string DirectoryName = "ClassStructs";

    /// <summary>The suffix every mirror carries.</summary>
    private const string MirrorSuffix = "ClassRaw";

    /// <summary>
    /// The width of a pointer, which is what the filler of a class struct union
    /// is measured in. Every target of this binding is 64 bit.
    /// </summary>
    private const int PointerWidth = 8;

    private readonly Repository _repository;
    private readonly EmissionCensus _census;
    private readonly DiagnosticBag _diagnostics;

    /// <summary>Initialises the emitter.</summary>
    /// <param name="repository">The loaded girs, for resolving field types.</param>
    /// <param name="census">The census of the run.</param>
    /// <param name="diagnostics">Where a field of an unmappable type is reported.</param>
    internal ClassStructEmitter(Repository repository, EmissionCensus census, DiagnosticBag diagnostics)
    {
        _repository = repository;
        _census = census;
        _diagnostics = diagnostics;
    }

    /// <summary>
    /// Returns the fully qualified name of the mirror of one class struct.
    /// </summary>
    /// <param name="model">The class struct.</param>
    /// <returns>The C# type name, for example <c>Gst.ElementClassRaw</c>.</returns>
    internal static string MirrorNameOf(ClassStructModel model) =>
        ModuleMap.ClrNamespaceOf(model.Namespace.Name) + "." + model.Owner.Name + MirrorSuffix;

    /// <summary>
    /// Returns the C# name of the member a class struct field is mirrored by.
    /// </summary>
    /// <param name="field">The field, as the gir spells it.</param>
    /// <returns>The C# identifier.</returns>
    internal static string MemberNameOf(GirField field) =>
        NameMapper.ToPascalCase(field.Name.TrimStart('_'));

    /// <summary>Emits the mirrors of one module.</summary>
    /// <param name="module">The module to emit.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <param name="subclasses">The class structs of the whole run.</param>
    /// <returns>The generated files, one per mirrored class.</returns>
    internal IReadOnlyList<GeneratedFile> Emit(ModuleInfo module, GirNamespace ns, SubclassModel subclasses)
    {
        List<GeneratedFile> files = [];
        List<ClassStructModel> mine = [];
        foreach (ClassStructModel model in subclasses.ClassStructs)
        {
            if (!ReferenceEquals(model.Namespace, ns))
            {
                continue;
            }

            mine.Add(model);
            files.Add(EmitOne(module, ns, model));
            _census.Emitted(module.GirNamespace, "class struct");
        }

        if (mine.Count > 0)
        {
            files.Add(EmitRegistry(module, ns, mine));
        }

        return files;
    }

    /// <summary>Emits the table the ABI probes of a module read.</summary>
    /// <param name="module">The module to emit.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <param name="models">The mirrors of the module.</param>
    /// <returns>The generated file.</returns>
    /// <remarks>
    /// The probe of the integration tests is written once rather than once per
    /// class: every mirror describes itself here, so a class that joins the
    /// allowlist joins the probe with it and the two cannot drift apart.
    /// </remarks>
    private static GeneratedFile EmitRegistry(ModuleInfo module, GirNamespace ns, IReadOnlyList<ClassStructModel> models)
    {
        CodeWriter writer = new();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("// Generated by GstSharp.Generator from " + ns.Name + "-" + ns.Version + ".gir. Do not edit.");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using System.Runtime.CompilerServices;");
        writer.WriteLine();
        writer.WriteLine("namespace " + module.ClrNamespace + ";");
        writer.WriteLine();
        writer.WriteLine("/// <summary>The class structs this module mirrors, for the ABI probes.</summary>");
        writer.WriteLine("internal static unsafe class ClassStructRegistry");
        writer.OpenBlock();
        writer.WriteLine("/// <summary>Builds the table of the mirrors of the module.</summary>");
        writer.WriteLine("/// <returns>One row per mirrored class struct.</returns>");
        writer.WriteLine("internal static Gst.GObject.ClassStructProbe[] CreateEntries() =>");
        writer.WriteLine("[");
        foreach (ClassStructModel model in models)
        {
            string mirror = MirrorNameOf(model);
            string wrapper = ModuleMap.ClrNamespaceOf(model.Namespace.Name) + "." + model.Owner.Name;
            writer.WriteLine("    new Gst.GObject.ClassStructProbe(");
            writer.WriteLine("        \"" + (model.TypeStruct.CType ?? model.TypeStruct.Name) + "\",");
            writer.WriteLine("        &" + wrapper + ".GetGType,");
            writer.WriteLine("        Unsafe.SizeOf<" + mirror + ">(),");
            writer.WriteLine("        [");
            foreach (ClassStructMember slot in model.Slots)
            {
                writer.WriteLine(
                    "            new Gst.GObject.ClassSlotProbe(\"" + slot.Method!.Name + "\", " + mirror + "."
                    + MemberNameOf(slot.Field) + "Offset),");
            }

            writer.WriteLine("        ]),");
        }

        writer.WriteLine("];");
        writer.CloseBlock();

        return new GeneratedFile(
            module.ProjectDirectory + "/Generated/" + DirectoryName + "/ClassStructRegistry.cs",
            writer.ToSource());
    }

    /// <summary>Emits the mirror of one class struct.</summary>
    /// <param name="module">The module the class belongs to.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <param name="model">The class struct to mirror.</param>
    /// <returns>The generated file.</returns>
    private GeneratedFile EmitOne(ModuleInfo module, GirNamespace ns, ClassStructModel model)
    {
        string mirror = model.Owner.Name + MirrorSuffix;
        string cName = model.TypeStruct.CType ?? model.TypeStruct.Name;

        CodeWriter writer = new();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("// Generated by GstSharp.Generator from " + ns.Name + "-" + ns.Version + ".gir. Do not edit.");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using System.Runtime.CompilerServices;");
        writer.WriteLine("using System.Runtime.InteropServices;");
        writer.WriteLine();
        writer.WriteLine("namespace " + module.ClrNamespace + ";");
        writer.WriteLine();
        writer.WriteLine("/// <summary>The native layout of <c>" + cName + "</c>.</summary>");
        writer.WriteLine("/// <remarks>");
        writer.WriteLine("/// <para>");
        writer.WriteLine("/// A class struct is not a table of function pointers: the mirror lays out");
        writer.WriteLine("/// every field the gir declares, data fields and reserved tail included,");
        writer.WriteLine("/// because the only thing the runtime does with it is write a function");
        writer.WriteLine("/// pointer at a computed offset. The slots are <see cref=\"nint\"/> rather");
        writer.WriteLine("/// than typed function pointers: whoever chains up through one casts it at");
        writer.WriteLine("/// the point of use. See <c>docs/subclassing.md</c> §6.1.");
        writer.WriteLine("/// </para>");
        writer.WriteLine("/// <para>");
        writer.WriteLine("/// The layout is asserted against the running library by the ABI probes of");
        writer.WriteLine("/// the integration tests, which compare it with the <c>class_size</c> that");
        writer.WriteLine("/// <c>g_type_query</c> reports.");
        writer.WriteLine("/// </para>");
        writer.WriteLine("/// </remarks>");
        writer.WriteLine("[StructLayout(LayoutKind.Sequential)]");
        writer.WriteLine("internal struct " + mirror);
        writer.OpenBlock();

        List<(string Name, int Length, string Element, string Doc)> inlineArrays = [];
        List<string> slots = [];
        bool first = true;

        // How many bytes of this class struct's own members stand in front of
        // the member being written, which is what says whether a union starts
        // on a pointer boundary. The embedded parent class struct at index 0
        // contributes nothing to the count: every class struct roots in
        // GTypeClass, whose first member is a GType, so its alignment is that
        // of a pointer and its size is a whole number of pointers by the C
        // rule that a structure is padded out to its own alignment.
        int offset = 0;
        for (int index = 0; index <= model.Members.Count; index++)
        {
            // The gir keeps the fields and the unions of a record in two lists,
            // so a union is placed by the number of fields it follows. Every
            // union of the allowlist is a trailing one, which is the index one
            // past the last field.
            foreach (GirUnion union in model.TypeStruct.Unions)
            {
                if (union.FieldIndex == index)
                {
                    EmitUnion(writer, module, ns, model, union, cName, offset, inlineArrays);
                    first = false;
                }
            }

            if (index == model.Members.Count)
            {
                break;
            }

            ClassStructMember member = model.Members[index];
            GirField field = member.Field;
            string name = MemberNameOf(field);
            if (!first)
            {
                writer.WriteLine();
            }

            first = false;

            if (index == 0)
            {
                // Every class struct opens with the class struct of the class
                // it derives from, by value: that embedding is what makes the
                // offsets of the derived slots come out right.
                writer.WriteLine("/// <summary>The <c>" + field.Name + "</c> field.</summary>");
                writer.WriteLine("internal " + ParentMirrorOf(model) + " " + name + ";");
                continue;
            }

            if (field.Type is GirArrayRef { FixedSize: > 0 } array)
            {
                string arrayType = name + "Array";
                inlineArrays.Add((
                    arrayType,
                    array.FixedSize.Value,
                    ScalarOf(array.ElementType, ns, field.Name),
                    "Inline storage of the " + Count(array.FixedSize.Value) + " elements the reserved tail of <c>"
                    + cName + "</c> is made of."));
                writer.WriteLine("/// <summary>The <c>" + field.Name + "</c> field.</summary>");
                writer.WriteLine("private " + arrayType + " " + Lowered(name) + ";");
                int element = WidthOf(ScalarOf(array.ElementType, ns, field.Name));
                offset = Align(offset, element) + (array.FixedSize.Value * element);
                continue;
            }

            if (member.IsSlot)
            {
                slots.Add(name);
                writer.WriteLine("/// <summary>The <c>" + field.Name + "</c> slot.</summary>");
                writer.WriteLine("internal nint " + name + ";");
                offset = Align(offset, PointerWidth) + PointerWidth;
                continue;
            }

            if (IsCallbackField(field, ns))
            {
                WriteOpaqueSlot(writer, module, model, field, name);
                offset = Align(offset, PointerWidth) + PointerWidth;
                continue;
            }

            string scalar = ScalarOf(field.Type, ns, field.Name);
            writer.WriteLine(
                "/// <summary>The <c>" + field.Name
                + "</c> field, which carries data rather than an overridable slot.</summary>");
            writer.WriteLine("internal " + scalar + " " + name + ";");
            offset = Align(offset, WidthOf(scalar)) + WidthOf(scalar);
        }

        if (slots.Count > 0)
        {
            writer.WriteLine();
            writer.WriteLine("static " + mirror + "()");
            writer.OpenBlock();
            writer.WriteLine(mirror + " probe = default;");
            foreach (string slot in slots)
            {
                writer.WriteLine(
                    slot + "Offset = Gst.GObject.ClassSlot.OffsetOf(ref probe, ref probe." + slot + ");");
            }

            writer.CloseBlock();

            foreach (string slot in slots)
            {
                writer.WriteLine();
                writer.WriteLine(
                    "/// <summary>Gets the byte offset of <see cref=\"" + slot
                    + "\"/> within the class struct, which is what a subclass declares the slot with.</summary>");
                writer.WriteLine("internal static int " + slot + "Offset { get; }");
            }
        }

        foreach ((string arrayType, int length, string element, string doc) in inlineArrays)
        {
            writer.WriteLine();
            writer.WriteLine("/// <summary>" + doc + "</summary>");
            writer.WriteLine("[InlineArray(" + Count(length) + ")]");
            writer.WriteLine("private struct " + arrayType);
            writer.OpenBlock();
            writer.WriteLine("private " + element + " _element0;");
            writer.CloseBlock();
        }

        writer.CloseBlock();
        return new GeneratedFile(
            module.ProjectDirectory + "/Generated/" + DirectoryName + "/" + mirror + ".cs",
            writer.ToSource());
    }

    /// <summary>Returns the type of the embedded parent class struct.</summary>
    /// <param name="model">The class struct.</param>
    /// <returns>The C# type name.</returns>
    /// <remarks>
    /// The chain stops where the girs of the GLib stack begin: the mirrors of
    /// <c>GObjectClass</c> and <c>GTypeClass</c> are hand written in the
    /// runtime, and <c>GInitiallyUnownedClass</c> is <c>GObjectClass</c> under
    /// another name, so both ends of the chain reach the same mirror.
    /// </remarks>
    private static string ParentMirrorOf(ClassStructModel model) =>
        model.Parent is { } parent ? MirrorNameOf(parent) : "Gst.GObject.GObjectClassRaw";

    /// <summary>Spells a count the way the invariant culture does.</summary>
    /// <param name="value">The count.</param>
    /// <returns>The decimal digits.</returns>
    private static string Count(int value) =>
        value.ToString(System.Globalization.CultureInfo.InvariantCulture);

    /// <summary>
    /// Lays a <c>&lt;union&gt;</c> of a class struct out as a block of the size
    /// of its largest member.
    /// </summary>
    /// <param name="writer">The writer of the mirror.</param>
    /// <param name="module">The module the class belongs to.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <param name="model">The class struct being mirrored.</param>
    /// <param name="union">The union to lay out.</param>
    /// <param name="cName">The C name of the class struct, for the documentation.</param>
    /// <param name="offset">
    /// How many bytes of the class struct's own members stand in front of the
    /// union, the embedded parent class struct not counted.
    /// </param>
    /// <param name="inlineArrays">Where the filler type is collected.</param>
    /// <remarks>
    /// <para>
    /// The unions of the GES class structs are all the same shape: a reserved
    /// array of pointers and, overlapping it, a record of the members later
    /// versions took out of that reserve. Only one member of a union can be
    /// spelled in a sequential mirror, and it is the record: it is what carries
    /// the fields whose offsets have to come out right. The reserve is what
    /// says how large the block is, and the difference between the two is
    /// written out as an explicit filler, because a mirror that stopped at the
    /// end of the record would be shorter than the C struct by the whole
    /// remainder of the reserve - which is 160 bytes on
    /// <c>GESClipClass</c> - and every class derived from it would carry the
    /// error.
    /// </para>
    /// <para>
    /// Nothing here pads by hand: the members of the record are written in gir
    /// order and the natural alignment of a sequential struct is the alignment
    /// the C compiler applied, so a <c>gboolean</c> in front of a pointer is
    /// followed by the same four bytes of padding in both. Only the trailing
    /// filler is computed, and it is computed for an eight byte pointer, which
    /// is what every target of this binding has.
    /// </para>
    /// <para>
    /// Two things the corpus does not contain are refused rather than laid out
    /// on a guess: a union that does not start on a pointer boundary, because
    /// the filler is measured in pointers from the start of the block, and a
    /// second <c>&lt;record&gt;</c> inside the union, because only one member
    /// of a union can be spelled in a sequential mirror and nothing here says
    /// which of two it should be.
    /// </para>
    /// </remarks>
    private void EmitUnion(
        CodeWriter writer,
        ModuleInfo module,
        GirNamespace ns,
        ClassStructModel model,
        GirUnion union,
        string cName,
        int offset,
        List<(string Name, int Length, string Element, string Doc)> inlineArrays)
    {
        if (offset % PointerWidth != 0)
        {
            _diagnostics.Error(
                "GEN0043",
                $"The union '{union.Name}' of the class struct '{cName}' follows {offset} bytes of members "
                + "of that class struct, which is not a whole number of pointers; the mirror lays a union "
                + "out on the assumption that it starts on a pointer boundary.");
            return;
        }

        if (union.Records.Count > 1)
        {
            _diagnostics.Error(
                "GEN0043",
                $"The union '{union.Name}' of the class struct '{cName}' declares {union.Records.Count} "
                + "records; only one member of a union can be spelled in a sequential mirror, and nothing "
                + "says which of these carries the offsets that have to come out right.");
            return;
        }

        // The gir spells a union name the way C does, and GES shouts it: ABI.
        // Lower casing first is what turns it into a C# identifier rather than
        // an ABIFiller nobody would write by hand.
        string block = NameMapper.ToPascalCase(union.Name.ToLowerInvariant());
        int size = SizeOfUnion(union, ns);
        int consumed = 0;

        // Every union of the corpus overlaps at most one record with its
        // reserve, and that record is the one the mirror spells: it is what
        // carries the fields whose offsets have to come out right. A union
        // with a second record was refused above.
        if (union.Records.Count > 0)
        {
            foreach (GirField field in union.Records[0].Fields)
            {
                string name = MemberNameOf(field);
                string type = IsCallbackField(field, ns) ? "nint" : ScalarOf(field.Type, ns, field.Name);
                consumed = Align(consumed, WidthOf(type));
                writer.WriteLine();
                if (IsCallbackField(field, ns))
                {
                    WriteOpaqueSlot(writer, module, model, field, name);
                }
                else
                {
                    writer.WriteLine(
                        "/// <summary>The <c>" + field.Name + "</c> field of the <c>" + union.Name
                        + "</c> union, which carries data rather than an overridable slot.</summary>");
                    writer.WriteLine("internal " + type + " " + name + ";");
                }

                consumed += WidthOf(type);
            }
        }

        int remaining = size - Align(consumed, PointerWidth);
        if (remaining < 0)
        {
            // The record is the largest member and it ends on something other
            // than a pointer boundary, so the block is shorter than the
            // members the mirror has already padded out to one.
            _diagnostics.Error(
                "GEN0043",
                $"The union '{union.Name}' of the class struct '{cName}' lays out {consumed} bytes of members, "
                + $"which the mirror pads to {Align(consumed, PointerWidth)}, inside a block measured at "
                + $"{size} bytes; the members do not fit in the block.");
            return;
        }

        if (remaining % PointerWidth != 0)
        {
            _diagnostics.Error(
                "GEN0043",
                $"The union '{union.Name}' of the class struct '{cName}' lays out {consumed} bytes of members "
                + $"inside a block of {size} bytes; the remainder is not a whole number of pointers, so the "
                + "mirror has no filler for it.");
            return;
        }

        if (remaining == 0)
        {
            return;
        }

        string filler = block + "Filler";
        writer.WriteLine();
        writer.WriteLine(
            "/// <summary>The unused tail of the <c>" + union.Name + "</c> union.</summary>");
        writer.WriteLine("private " + filler + " " + Lowered(filler) + ";");
        inlineArrays.Add((
            filler,
            remaining / PointerWidth,
            "nint",
            "Inline storage of the " + Count(remaining / PointerWidth) + " pointers that pad the <c>"
            + union.Name + "</c> union of <c>" + cName + "</c> out to the size of its largest member."));
    }

    /// <summary>Measures a class struct union, which is its largest member.</summary>
    /// <param name="union">The union to measure.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <returns>The size in bytes.</returns>
    private int SizeOfUnion(GirUnion union, GirNamespace ns)
    {
        int size = 0;
        foreach (GirField field in union.Fields)
        {
            size = Math.Max(size, SizeOfField(field, ns));
        }

        foreach (GirRecord record in union.Records)
        {
            int consumed = 0;
            int alignment = 1;
            foreach (GirField field in record.Fields)
            {
                int width = SizeOfField(field, ns);
                int fieldAlignment = AlignmentOfField(field, ns);
                alignment = Math.Max(alignment, fieldAlignment);
                consumed = Align(consumed, fieldAlignment) + width;
            }

            size = Math.Max(size, Align(consumed, alignment));
        }

        return size;
    }

    /// <summary>Measures one field of a union, in bytes.</summary>
    /// <param name="field">The field, as the gir spells it.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <returns>The size in bytes.</returns>
    private int SizeOfField(GirField field, GirNamespace ns) =>
        field.Type is GirArrayRef { FixedSize: > 0 } array
            ? array.FixedSize.Value * WidthOf(ScalarOf(array.ElementType, ns, field.Name))
            : AlignmentOfField(field, ns);

    /// <summary>Returns the alignment one field of a union is laid out on.</summary>
    /// <param name="field">The field, as the gir spells it.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <returns>The alignment in bytes, which for every scalar here is its width.</returns>
    private int AlignmentOfField(GirField field, GirNamespace ns) =>
        field.Type is GirArrayRef { FixedSize: > 0 } array
            ? WidthOf(ScalarOf(array.ElementType, ns, field.Name))
            : WidthOf(IsCallbackField(field, ns) ? "nint" : ScalarOf(field.Type, ns, field.Name));

    /// <summary>Rounds an offset up to an alignment.</summary>
    /// <param name="offset">The offset so far.</param>
    /// <param name="alignment">The alignment to round to.</param>
    /// <returns>The rounded offset.</returns>
    private static int Align(int offset, int alignment) =>
        (offset + alignment - 1) / alignment * alignment;

    /// <summary>Returns the width of one of the types a mirror lays fields out with.</summary>
    /// <param name="type">The C# type name the mirror uses.</param>
    /// <returns>The width in bytes.</returns>
    /// <remarks>
    /// Only the four byte types are named: everything else a class struct field
    /// maps onto - a pointer, a 64 bit integer, a double - is the width of a
    /// pointer on every target of this binding, all of which are 64 bit.
    /// </remarks>
    private static int WidthOf(string type) =>
        type is "int" or "uint" or "float" ? 4 : PointerWidth;

    /// <summary>
    /// Tests whether a class struct field holds a function pointer, whether the
    /// gir spells it as an inline <c>&lt;callback&gt;</c> or as a named callback
    /// typedef.
    /// </summary>
    /// <param name="field">The field, as the gir spells it.</param>
    /// <param name="ns">The namespace the field is declared in.</param>
    /// <returns><see langword="true"/> when the field is a function pointer.</returns>
    /// <remarks>
    /// The two spellings mean the same thing to the C compiler and the mirror
    /// treats them the same way, but only the inline one carries a signature
    /// the pairing can read, which is why a field of either shape that is not
    /// an overridable slot ends up here rather than in the data branch. The
    /// question itself is <see cref="SubclassModel.IsFunctionPointerField"/>,
    /// which is what the pairing asks, so the two cannot drift apart.
    /// </remarks>
    private bool IsCallbackField(GirField field, GirNamespace ns) =>
        SubclassModel.IsFunctionPointerField(_repository, ns, field);

    /// <summary>
    /// Lays a function pointer field out that carries no managed surface, and
    /// says so in the ledger.
    /// </summary>
    /// <param name="writer">The writer of the mirror.</param>
    /// <param name="module">The module the class belongs to.</param>
    /// <param name="model">The class struct being mirrored.</param>
    /// <param name="field">The field, as the gir spells it.</param>
    /// <param name="name">The C# name of the member.</param>
    /// <remarks>
    /// A slot the planner refused is listed by <c>VfuncEmitter</c>; this is the
    /// other half of the same statement, for a field that never reached the
    /// planner because no <c>&lt;virtual-method&gt;</c> stands beside it. The
    /// two together are what makes the <c>## Virtuals</c> section of the skip
    /// report the whole list of C slots without an <c>OnX</c> member.
    /// </remarks>
    private void WriteOpaqueSlot(
        CodeWriter writer,
        ModuleInfo module,
        ClassStructModel model,
        GirField field,
        string name)
    {
        _census.SkippedVirtual(
            module.GirNamespace,
            model.KeyOf(field.Name),
            nameof(SkipReason.OpaqueSlot));
        writer.WriteLine(
            "/// <summary>The <c>" + field.Name
            + "</c> field, a function pointer no managed surface overrides.</summary>");
        writer.WriteLine("internal nint " + name + ";");
    }

    /// <summary>Spells a member name the way a private field is spelled.</summary>
    /// <param name="name">The Pascal cased member name.</param>
    /// <returns>The field name.</returns>
    private static string Lowered(string name) => "_" + char.ToLowerInvariant(name[0]) + name[1..];

    /// <summary>
    /// Maps the type of a data field onto the blittable type that occupies the
    /// same storage.
    /// </summary>
    /// <param name="type">The gir type, or <see langword="null"/> for none.</param>
    /// <param name="ns">The namespace the field is declared in.</param>
    /// <param name="fieldName">The field, for the diagnostic.</param>
    /// <returns>The C# type name.</returns>
    /// <remarks>
    /// The mirror never projects a data field onto a wrapper: a class struct is
    /// read once, to measure it, and a field that is not a slot is only there so
    /// that the slots after it land where the C compiler put them. Anything
    /// pointer sized is therefore an <see langword="nint"/>, whatever it points
    /// at.
    /// </remarks>
    private string ScalarOf(GirTypeRef? type, GirNamespace ns, string fieldName)
    {
        string? name = type?.Name;
        string? cType = type?.CType;
        if (cType is not null && cType.EndsWith('*'))
        {
            return "nint";
        }

        switch (name)
        {
            case "gpointer" or "gconstpointer" or "utf8" or "filename":
                return "nint";
            case "gboolean" or "gint" or "gint32":
                return "int";
            case "guint" or "guint32":
                return "uint";
            case "gint64":
                return "long";
            case "guint64":
                return "ulong";
            case "gsize":
                return "nuint";
            case "gssize":
                return "nint";

            // A C long is 32 bits wide on Windows and 64 on every other target
            // of this binding, so no single managed type mirrors it and a guess
            // would shift every field behind it. No class struct of the
            // allowlist has one; this says so rather than laying one out wrong.
            case "glong" or "gulong":
                _diagnostics.Error(
                    "GEN0035",
                    $"The class struct field '{fieldName}' has the type '{name}', whose width differs between "
                    + "Windows and the other targets; the mirror has no type for it.");
                return "nint";
            case "gfloat":
                return "float";
            case "gdouble":
                return "double";
            default:
                break;
        }

        // An enumeration is an int in every gir of this stack; anything else
        // that resolves to a declared type here would be a struct embedded by
        // value, which no class struct of the allowlist does.
        if (name is not null
            && _repository.Resolve(name, ns) is { Kind: GirSymbolKind.Enumeration })
        {
            return "int";
        }

        _diagnostics.Warn(
            "GEN0032",
            $"The class struct field '{fieldName}' has the type '{name ?? "(none)"}', which the mirror cannot "
            + "lay out; it is mirrored as a pointer, which is wrong unless the field is one.");
        return "nint";
    }
}
