using GstSharp.Generator.GirParsing.Model;
using GstSharp.Generator.Semantic;

namespace GstSharp.Generator.Emit;

/// <summary>
/// Emits the managed mirror of a class struct, one file per class.
/// </summary>
/// <remarks>
/// <para>
/// The runtime does exactly one thing with a class struct: it writes a function
/// pointer at a computed offset. Everything else the mirror carries is there so
/// that the offset comes out right, which is why the mirror lays out every
/// field the gir declares — the data fields a <c>class_init</c> writes, the
/// slots nothing overrides, and the reserved tail — and why no field of it is
/// ever a typed <c>delegate*</c>: a slot is read as an <see langword="nint"/>
/// and cast at the point of use.
/// </para>
/// <para>
/// The offsets are measured from the mirror at run time rather than written out
/// as literals, so a declaration cannot drift from the layout; the layout
/// itself is what the ABI probes pin to the running library.
/// </para>
/// </remarks>
internal sealed class ClassStructEmitter
{
    /// <summary>The directory the mirrors are written to, below <c>Generated</c>.</summary>
    internal const string DirectoryName = "ClassStructs";

    /// <summary>The suffix every mirror carries.</summary>
    private const string MirrorSuffix = "ClassRaw";

    private readonly Repository _repository;
    private readonly EmissionCensus _census;
    private readonly DiagnosticBag _diagnostics;

    /// <summary>Initialises the emitter.</summary>
    /// <param name="repository">The loaded girs, for resolving field types.</param>
    /// <param name="census">The census of the run.</param>
    /// <param name="diagnostics">Where a field of an unmappable type is reported.</param>
    internal ClassStructEmitter(Repository repository, EmissionCensus census, DiagnosticBag diagnostics)
    {
        _repository = repository;
        _census = census;
        _diagnostics = diagnostics;
    }

    /// <summary>
    /// Returns the fully qualified name of the mirror of one class struct.
    /// </summary>
    /// <param name="model">The class struct.</param>
    /// <returns>The C# type name, for example <c>Gst.ElementClassRaw</c>.</returns>
    internal static string MirrorNameOf(ClassStructModel model) =>
        ModuleMap.ClrNamespaceOf(model.Namespace.Name) + "." + model.Owner.Name + MirrorSuffix;

    /// <summary>
    /// Returns the C# name of the member a class struct field is mirrored by.
    /// </summary>
    /// <param name="field">The field, as the gir spells it.</param>
    /// <returns>The C# identifier.</returns>
    internal static string MemberNameOf(GirField field) =>
        NameMapper.ToPascalCase(field.Name.TrimStart('_'));

    /// <summary>Emits the mirrors of one module.</summary>
    /// <param name="module">The module to emit.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <param name="subclasses">The class structs of the whole run.</param>
    /// <returns>The generated files, one per mirrored class.</returns>
    internal IReadOnlyList<GeneratedFile> Emit(ModuleInfo module, GirNamespace ns, SubclassModel subclasses)
    {
        List<GeneratedFile> files = [];
        foreach (ClassStructModel model in subclasses.ClassStructs)
        {
            if (!ReferenceEquals(model.Namespace, ns))
            {
                continue;
            }

            files.Add(EmitOne(module, ns, model));
            _census.Emitted(module.GirNamespace, "class struct");
        }

        return files;
    }

    /// <summary>Emits the mirror of one class struct.</summary>
    /// <param name="module">The module the class belongs to.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <param name="model">The class struct to mirror.</param>
    /// <returns>The generated file.</returns>
    private GeneratedFile EmitOne(ModuleInfo module, GirNamespace ns, ClassStructModel model)
    {
        string mirror = model.Owner.Name + MirrorSuffix;
        string cName = model.TypeStruct.CType ?? model.TypeStruct.Name;

        CodeWriter writer = new();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("// Generated by GstSharp.Generator from " + ns.Name + "-" + ns.Version + ".gir. Do not edit.");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using System.Runtime.CompilerServices;");
        writer.WriteLine("using System.Runtime.InteropServices;");
        writer.WriteLine();
        writer.WriteLine("namespace " + module.ClrNamespace + ";");
        writer.WriteLine();
        writer.WriteLine("/// <summary>The native layout of <c>" + cName + "</c>.</summary>");
        writer.WriteLine("/// <remarks>");
        writer.WriteLine("/// <para>");
        writer.WriteLine("/// A class struct is not a table of function pointers: the mirror lays out");
        writer.WriteLine("/// every field the gir declares, data fields and reserved tail included,");
        writer.WriteLine("/// because the only thing the runtime does with it is write a function");
        writer.WriteLine("/// pointer at a computed offset. The slots are <see cref=\"nint\"/> rather");
        writer.WriteLine("/// than typed function pointers: whoever chains up through one casts it at");
        writer.WriteLine("/// the point of use. See <c>docs/subclassing.md</c> §6.1.");
        writer.WriteLine("/// </para>");
        writer.WriteLine("/// <para>");
        writer.WriteLine("/// The layout is asserted against the running library by the ABI probes of");
        writer.WriteLine("/// the integration tests, which compare it with the <c>class_size</c> that");
        writer.WriteLine("/// <c>g_type_query</c> reports.");
        writer.WriteLine("/// </para>");
        writer.WriteLine("/// </remarks>");
        writer.WriteLine("[StructLayout(LayoutKind.Sequential)]");
        writer.WriteLine("internal struct " + mirror);
        writer.OpenBlock();

        List<(string Name, int Length, string Element)> inlineArrays = [];
        List<string> slots = [];
        bool first = true;
        for (int index = 0; index < model.Members.Count; index++)
        {
            ClassStructMember member = model.Members[index];
            GirField field = member.Field;
            string name = MemberNameOf(field);
            if (!first)
            {
                writer.WriteLine();
            }

            first = false;

            if (index == 0)
            {
                // Every class struct opens with the class struct of the class
                // it derives from, by value: that embedding is what makes the
                // offsets of the derived slots come out right.
                writer.WriteLine("/// <summary>The <c>" + field.Name + "</c> field.</summary>");
                writer.WriteLine("internal " + ParentMirrorOf(model) + " " + name + ";");
                continue;
            }

            if (field.Type is GirArrayRef { FixedSize: > 0 } array)
            {
                string arrayType = name + "Array";
                inlineArrays.Add((arrayType, array.FixedSize.Value, ScalarOf(array.ElementType, ns, field.Name)));
                writer.WriteLine("/// <summary>The <c>" + field.Name + "</c> field.</summary>");
                writer.WriteLine("private " + arrayType + " " + Lowered(name) + ";");
                continue;
            }

            if (member.IsSlot)
            {
                slots.Add(name);
                writer.WriteLine("/// <summary>The <c>" + field.Name + "</c> slot.</summary>");
                writer.WriteLine("internal nint " + name + ";");
                continue;
            }

            writer.WriteLine(
                "/// <summary>The <c>" + field.Name
                + "</c> field, which carries data rather than an overridable slot.</summary>");
            writer.WriteLine("internal " + ScalarOf(field.Type, ns, field.Name) + " " + name + ";");
        }

        if (slots.Count > 0)
        {
            writer.WriteLine();
            writer.WriteLine("static " + mirror + "()");
            writer.OpenBlock();
            writer.WriteLine(mirror + " probe = default;");
            foreach (string slot in slots)
            {
                writer.WriteLine(
                    slot + "Offset = Gst.GObject.ClassSlot.OffsetOf(ref probe, ref probe." + slot + ");");
            }

            writer.CloseBlock();

            foreach (string slot in slots)
            {
                writer.WriteLine();
                writer.WriteLine(
                    "/// <summary>Gets the byte offset of <see cref=\"" + slot
                    + "\"/> within the class struct, which is what a subclass declares the slot with.</summary>");
                writer.WriteLine("internal static int " + slot + "Offset { get; }");
            }
        }

        foreach ((string arrayType, int length, string element) in inlineArrays)
        {
            writer.WriteLine();
            writer.WriteLine(
                "/// <summary>Inline storage of the " + length.ToString(System.Globalization.CultureInfo.InvariantCulture)
                + " elements the reserved tail of <c>" + cName + "</c> is made of.</summary>");
            writer.WriteLine(
                "[InlineArray(" + length.ToString(System.Globalization.CultureInfo.InvariantCulture) + ")]");
            writer.WriteLine("private struct " + arrayType);
            writer.OpenBlock();
            writer.WriteLine("private " + element + " _element0;");
            writer.CloseBlock();
        }

        writer.CloseBlock();
        return new GeneratedFile(
            module.ProjectDirectory + "/Generated/" + DirectoryName + "/" + mirror + ".cs",
            writer.ToSource());
    }

    /// <summary>Returns the type of the embedded parent class struct.</summary>
    /// <param name="model">The class struct.</param>
    /// <returns>The C# type name.</returns>
    /// <remarks>
    /// The chain stops where the girs of the GLib stack begin: the mirrors of
    /// <c>GObjectClass</c> and <c>GTypeClass</c> are hand written in the
    /// runtime, and <c>GInitiallyUnownedClass</c> is <c>GObjectClass</c> under
    /// another name, so both ends of the chain reach the same mirror.
    /// </remarks>
    private static string ParentMirrorOf(ClassStructModel model) =>
        model.Parent is { } parent ? MirrorNameOf(parent) : "Gst.GObject.GObjectClassRaw";

    /// <summary>Spells a member name the way a private field is spelled.</summary>
    /// <param name="name">The Pascal cased member name.</param>
    /// <returns>The field name.</returns>
    private static string Lowered(string name) => "_" + char.ToLowerInvariant(name[0]) + name[1..];

    /// <summary>
    /// Maps the type of a data field onto the blittable type that occupies the
    /// same storage.
    /// </summary>
    /// <param name="type">The gir type, or <see langword="null"/> for none.</param>
    /// <param name="ns">The namespace the field is declared in.</param>
    /// <param name="fieldName">The field, for the diagnostic.</param>
    /// <returns>The C# type name.</returns>
    /// <remarks>
    /// The mirror never projects a data field onto a wrapper: a class struct is
    /// read once, to measure it, and a field that is not a slot is only there so
    /// that the slots after it land where the C compiler put them. Anything
    /// pointer sized is therefore an <see langword="nint"/>, whatever it points
    /// at.
    /// </remarks>
    private string ScalarOf(GirTypeRef? type, GirNamespace ns, string fieldName)
    {
        string? name = type?.Name;
        string? cType = type?.CType;
        if (cType is not null && cType.EndsWith('*'))
        {
            return "nint";
        }

        switch (name)
        {
            case "gpointer" or "gconstpointer" or "utf8" or "filename":
                return "nint";
            case "gboolean" or "gint" or "gint32":
                return "int";
            case "guint" or "guint32":
                return "uint";
            case "gint64":
                return "long";
            case "guint64":
                return "ulong";
            case "gsize":
                return "nuint";
            case "gssize" or "glong":
                return "nint";
            case "gulong":
                return "nuint";
            case "gfloat":
                return "float";
            case "gdouble":
                return "double";
            default:
                break;
        }

        // An enumeration is an int in every gir of this stack; anything else
        // that resolves to a declared type here would be a struct embedded by
        // value, which no class struct of the allowlist does.
        if (name is not null
            && _repository.Resolve(name, ns) is { Kind: GirSymbolKind.Enumeration })
        {
            return "int";
        }

        _diagnostics.Warn(
            "GEN0032",
            $"The class struct field '{fieldName}' has the type '{name ?? "(none)"}', which the mirror cannot "
            + "lay out; it is mirrored as a pointer, which is wrong unless the field is one.");
        return "nint";
    }
}
