using System.Globalization;
using GstSharp.Generator.GirParsing.Model;
using GstSharp.Generator.Semantic;

namespace GstSharp.Generator.Emit;

/// <summary>
/// Emits every <c>&lt;enumeration&gt;</c> and <c>&lt;bitfield&gt;</c> of a gir
/// namespace into a single <c>Generated/Enums.cs</c> file.
/// </summary>
internal sealed class EnumEmitter
{
    private readonly NameMapper _names;
    private readonly Overlays _overlays;
    private readonly DiagnosticBag _diagnostics;

    /// <summary>Initializes a new instance of the <see cref="EnumEmitter"/> class.</summary>
    /// <param name="names">The name mapper.</param>
    /// <param name="overlays">The overlay configuration.</param>
    /// <param name="diagnostics">The diagnostic sink.</param>
    internal EnumEmitter(NameMapper names, Overlays overlays, DiagnosticBag diagnostics)
    {
        _names = names;
        _overlays = overlays;
        _diagnostics = diagnostics;
    }

    /// <summary>Emits the enumerations of one module.</summary>
    /// <param name="module">The module to emit.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <returns>The generated file, or <see langword="null"/> when the namespace has no enumerations.</returns>
    internal GeneratedFile? Emit(ModuleInfo module, GirNamespace ns)
    {
        List<GirEnumeration> enumerations = [];
        foreach (GirEnumeration enumeration in ns.AllEnumerations)
        {
            if (_overlays.IsSkipped(ns.Name + "." + enumeration.Name) || !enumeration.IsIntrospectable)
            {
                continue;
            }

            enumerations.Add(enumeration);
        }

        if (enumerations.Count == 0)
        {
            return null;
        }

        // Types are ordered by their C# name so that the file stays stable when
        // the gir reorders declarations.
        enumerations.Sort((left, right) => string.CompareOrdinal(TypeNameOf(ns, left), TypeNameOf(ns, right)));

        bool needsSystem = false;
        foreach (GirEnumeration enumeration in enumerations)
        {
            needsSystem |= enumeration.IsBitfield || enumeration.IsDeprecated;
            foreach (GirEnumMember member in enumeration.Members)
            {
                needsSystem |= member.IsDeprecated;
            }
        }

        CodeWriter writer = new();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"// Generated by GstSharp.Generator from {ns.Name}-{ns.Version}.gir. Do not edit."));
        writer.WriteLine();

        if (needsSystem)
        {
            writer.WriteLine("using System;");
            writer.WriteLine();
        }

        writer.WriteLine("namespace " + module.ClrNamespace + ";");

        foreach (GirEnumeration enumeration in enumerations)
        {
            writer.WriteLine();
            WriteEnumeration(writer, ns, enumeration);
        }

        return new GeneratedFile(module.ProjectDirectory + "/Generated/Enums.cs", writer.ToSource());
    }

    private static string FallbackSummary(GirEnumeration enumeration) =>
        enumeration.CType is { Length: > 0 } cType
            ? $"The <c>{cType}</c> {(enumeration.IsBitfield ? "flags" : "enumeration")}."
            : $"The <c>{enumeration.Name}</c> {(enumeration.IsBitfield ? "flags" : "enumeration")}.";

    private static string FallbackSummary(GirEnumeration enumeration, GirEnumMember member) =>
        member.CIdentifier is { Length: > 0 } identifier
            ? $"The <c>{identifier}</c> value."
            : $"The <c>{enumeration.Name}.{member.Name}</c> value.";

    private static string FormatValue(GirEnumeration enumeration, long value)
    {
        if (!enumeration.IsBitfield)
        {
            return value.ToString(CultureInfo.InvariantCulture);
        }

        return "0x" + ((uint)value).ToString("X8", CultureInfo.InvariantCulture);
    }

    private string TypeNameOf(GirNamespace ns, GirEnumeration enumeration) =>
        _names.TypeName(new GirSymbol(ns, enumeration.Name, GirSymbolKind.Enumeration, enumeration));

    private void WriteEnumeration(CodeWriter writer, GirNamespace ns, GirEnumeration enumeration)
    {
        XmlDocWriter.Write(writer, enumeration.Doc, FallbackSummary(enumeration));
        XmlDocWriter.WriteObsolete(writer, enumeration);
        if (enumeration.IsBitfield)
        {
            writer.WriteLine("[Flags]");
        }

        EnumUnderlyingType underlyingType = EnumFacts.GetUnderlyingType(enumeration, _diagnostics);
        string declaration = "public enum " + TypeNameOf(ns, enumeration);
        if (underlyingType == EnumUnderlyingType.UInt32)
        {
            declaration += " : " + EnumFacts.ToKeyword(underlyingType);
        }

        writer.WriteLine(declaration);
        writer.OpenBlock();

        HashSet<string> emitted = new(StringComparer.Ordinal);
        bool first = true;
        foreach (GirEnumMember member in enumeration.Members)
        {
            if (!EnumFacts.TryParseValue(member.Value, out long value))
            {
                continue;
            }

            string name = _names.EnumMemberName(enumeration, ns, member);
            string literal = FormatValue(enumeration, value);
            if (!emitted.Add(name + "=" + literal))
            {
                // The gir repeats members verbatim when a C macro combines
                // flags, for example GST_VIDEO_FRAME_FLAG_ONEFIELD.
                continue;
            }

            if (!emitted.Add(name))
            {
                _diagnostics.Warn(
                    "GEN0004",
                    $"Enumeration '{ns.Name}.{enumeration.Name}' declares '{name}' more than once with different values; the later declaration is dropped.");
                continue;
            }

            if (!first)
            {
                writer.WriteLine();
            }

            first = false;
            XmlDocWriter.Write(writer, member.Doc, FallbackSummary(enumeration, member));
            XmlDocWriter.WriteObsolete(writer, member);
            writer.WriteLine(name + " = " + literal + ",");
        }

        writer.CloseBlock();
    }
}
