using GstSharp.Generator.GirParsing.Model;
using GstSharp.Generator.Semantic;

namespace GstSharp.Generator.Emit;

/// <summary>
/// Emits the type table that a generated module hands to
/// <c>Gst.GObject.TypeRegistry</c>.
/// </summary>
/// <remarks>
/// <para>
/// The table is a plain array of function pointers, so nothing about it is
/// resolved before the native libraries are loaded and nothing about it needs
/// reflection. Every entry names the <c>glib:get-type</c> import and the
/// factory of one generated wrapper.
/// </para>
/// <para>
/// The file declares the same <c>partial</c> class as the hand written module
/// initialiser of the binding assembly, which only has to pass
/// <c>CreateEntries()</c> to the <c>NativeModule</c> it builds.
/// </para>
/// </remarks>
internal sealed class RegistryEmitter
{
    /// <summary>The name of the generated file, below the <c>Generated</c> directory.</summary>
    internal const string FileName = "_Module.cs";

    /// <summary>Emits the type table of one module.</summary>
    /// <param name="module">The module to emit.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <param name="types">The fully qualified names of the registered wrappers.</param>
    /// <returns>The generated file.</returns>
    internal GeneratedFile Emit(ModuleInfo module, GirNamespace ns, IReadOnlyList<string> types)
    {
        List<string> ordered = [.. types];
        ordered.Sort(StringComparer.Ordinal);

        CodeWriter writer = new();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("// Generated by GstSharp.Generator from " + ns.Name + "-" + ns.Version + ".gir. Do not edit.");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("namespace " + module.ClrNamespace + ";");
        writer.WriteLine();
        writer.WriteLine("/// <summary>The generated part of the module registration of this assembly.</summary>");
        writer.WriteLine("internal static unsafe partial class " + ModuleClassName(module));
        writer.OpenBlock();
        writer.WriteLine("/// <summary>Builds the type table of the module.</summary>");
        writer.WriteLine("/// <returns>One entry per generated wrapper that GObject knows a type for.</returns>");
        writer.WriteLine("internal static Gst.Interop.ModuleTypeEntry[] CreateEntries() =>");
        writer.WriteLine("[");
        foreach (string type in ordered)
        {
            writer.WriteLine(
                "    new Gst.Interop.ModuleTypeEntry(&" + type + ".GetGType, &" + type + ".CreateWrapper),");
        }

        writer.WriteLine("];");
        writer.CloseBlock();

        return new GeneratedFile(module.ProjectDirectory + "/Generated/" + FileName, writer.ToSource());
    }

    /// <summary>Returns the name of the module registration class of a module.</summary>
    /// <param name="module">The module to name.</param>
    /// <returns>The C# class name, for example <c>GstModule</c>.</returns>
    internal static string ModuleClassName(ModuleInfo module) => module.GirNamespace + "Module";
}
