using GstSharp.Generator.GirParsing.Model;
using GstSharp.Generator.Semantic;

namespace GstSharp.Generator.Emit;

/// <summary>
/// One row of the type table of a module.
/// </summary>
/// <param name="TypeName">The fully qualified name of the generated wrapper.</param>
/// <param name="IsDeprecated">
/// Whether the wrapper carries an <c>[Obsolete]</c> attribute, which the table
/// has to name it despite.
/// </param>
internal sealed record RegistryEntry(string TypeName, bool IsDeprecated);

/// <summary>
/// Emits the type table that a generated module hands to
/// <c>Gst.GObject.TypeRegistry</c>.
/// </summary>
/// <remarks>
/// <para>
/// The table is a plain array of function pointers, so nothing about it is
/// resolved before the native libraries are loaded and nothing about it needs
/// reflection. Every entry names the <c>glib:get-type</c> import and the
/// factory of one generated wrapper.
/// </para>
/// <para>
/// The file declares the same <c>partial</c> class as the hand written module
/// initialiser of the binding assembly, which only has to pass
/// <c>CreateEntries()</c> to the <c>NativeModule</c> it builds.
/// </para>
/// </remarks>
internal sealed class RegistryEmitter
{
    /// <summary>The name of the generated file, below the <c>Generated</c> directory.</summary>
    internal const string FileName = "_Module.cs";

    /// <summary>Emits the type table of one module.</summary>
    /// <param name="module">The module to emit.</param>
    /// <param name="ns">The gir namespace of the module.</param>
    /// <param name="types">The registered wrappers.</param>
    /// <returns>The generated file.</returns>
    internal GeneratedFile Emit(ModuleInfo module, GirNamespace ns, IReadOnlyList<RegistryEntry> types)
    {
        List<RegistryEntry> ordered = [.. types];
        ordered.Sort(static (left, right) => string.CompareOrdinal(left.TypeName, right.TypeName));

        bool anyDeprecated = false;
        foreach (RegistryEntry entry in ordered)
        {
            anyDeprecated |= entry.IsDeprecated;
        }

        CodeWriter writer = new();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("// Generated by GstSharp.Generator from " + ns.Name + "-" + ns.Version + ".gir. Do not edit.");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("namespace " + module.ClrNamespace + ";");
        writer.WriteLine();
        writer.WriteLine("/// <summary>The generated part of the module registration of this assembly.</summary>");
        writer.WriteLine("internal static unsafe partial class " + ModuleClassName(module));
        writer.OpenBlock();
        if (anyDeprecated)
        {
            // The table is the one place outside the file of a deprecated
            // wrapper that names it, so it is the one place that needs the
            // pragma; inside the wrapper the compiler reports nothing, because
            // a use of an obsolete member inside an obsolete member is allowed.
            // The pragma is emitted only when it suppresses something, and it
            // states in the output why it is there.
            writer.WriteLine("// The module registers its deprecated wrappers too: the deprecation is a");
            writer.WriteLine("// message to the callers of a type, while the registry still has to map");
            writer.WriteLine("// the GType of every wrapper native code can hand back.");
            writer.WriteLine("#pragma warning disable CS0618");
        }

        writer.WriteLine("/// <summary>Builds the type table of the module.</summary>");
        writer.WriteLine("/// <returns>One entry per generated wrapper that GObject knows a type for.</returns>");
        writer.WriteLine("internal static Gst.Interop.ModuleTypeEntry[] CreateEntries() =>");
        writer.WriteLine("[");
        foreach (RegistryEntry entry in ordered)
        {
            writer.WriteLine(
                "    new Gst.Interop.ModuleTypeEntry(&" + entry.TypeName + ".GetGType, &"
                + entry.TypeName + ".CreateWrapper),");
        }

        writer.WriteLine("];");
        if (anyDeprecated)
        {
            writer.WriteLine("#pragma warning restore CS0618");
        }

        writer.CloseBlock();

        return new GeneratedFile(module.ProjectDirectory + "/Generated/" + FileName, writer.ToSource());
    }

    /// <summary>Returns the name of the module registration class of a module.</summary>
    /// <param name="module">The module to name.</param>
    /// <returns>The C# class name, for example <c>GstModule</c>.</returns>
    internal static string ModuleClassName(ModuleInfo module) => module.GirNamespace + "Module";
}
